# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: /home/xilinx/LPSC_project/Mandelbrot/designs/hw/mandelbrot_pinout/src/constrs/mandelbrot_pinout.xdc

# IP: ip/clk_mandelbrot/clk_mandelbrot.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==clk_mandelbrot || ORIG_REF_NAME==clk_mandelbrot} -quiet] -quiet
