# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: /home/xilinx/LPSC_project/Mandelbrot/designs/hw/mandelbrot_pinout/src/constrs/mandelbrot_pinout.xdc

# IP: ip/bram_video_memory_wauto_dauto_rdclk1_wrclk1/bram_video_memory_wauto_dauto_rdclk1_wrclk1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bram_video_memory_wauto_dauto_rdclk1_wrclk1 || ORIG_REF_NAME==bram_video_memory_wauto_dauto_rdclk1_wrclk1} -quiet] -quiet
