# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/xilinx/LPSC_project/Mandelbrot/designs/vivado/mandelbrot_pinout/2018.2/mandelbrot_pinout.srcs/sources_1/ip/mathDSP/mathDSP.xci
# IP: The module: 'mathDSP' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/xilinx/LPSC_project/Mandelbrot/designs/vivado/mandelbrot_pinout/2018.2/mandelbrot_pinout.srcs/sources_1/ip/mathDSP/mathDSP_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mathDSP'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: /home/xilinx/LPSC_project/Mandelbrot/designs/vivado/mandelbrot_pinout/2018.2/mandelbrot_pinout.srcs/sources_1/ip/mathDSP/mathDSP.xci
# IP: The module: 'mathDSP' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/xilinx/LPSC_project/Mandelbrot/designs/vivado/mandelbrot_pinout/2018.2/mandelbrot_pinout.srcs/sources_1/ip/mathDSP/mathDSP_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mathDSP'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
